name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=black&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39
            dist/github-snake-dark.svg?palette=github-dark&color_snake=black

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cp dist/github-snake.svg dist/github-snake-dark.svg ./
          git add github-snake.svg github-snake-dark.svg
          git diff --staged --quiet || git commit -m "update snake"
          git push
